Shop/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Shop.Controllers
{
    public class CarsController :Controller
    {
        private readonly IAllCars _allCars;
        
        private readonly ICarsCategory _allCatgories;

        public CarsController(IAllCars IallCars, ICarsCategory IcarsCategory)
        {
            _allCars = IallCars;
            _allCatgories = IcarsCategory;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Car> cars=null;
            string carCategory = "";
            if (string.IsNullOrEmpty(_category))
            {
                cars = _allCars.AllCars.OrderBy(i => i.id);

            }
            else
            {
                if(string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.AllCars.Where(i => i.Category.Equals("Электромобиль")).OrderBy(i=>i.id);
                    carCategory = "Электромобиль";
                }
                else
                {
                    cars = _allCars.AllCars.Where(i => i.Category.Equals("Классический автомобиль")).OrderBy(i => i.id);
                    carCategory = "Классический автомобиль";
                }
                
            }
           
            var Carobj = new CarsListViewModel
            {
              allCars=cars,
              currentCategory= carCategory
            };




            ViewBag.Title = "Страница с автомобилями";
            //CarsListViewModel obj = new CarsListViewModel();
           // obj.allCars = _allCars.AllCars;
            //obj.currentCategory = "Автомобили";
            return View(Carobj); 
        }

    }
}

Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCars _carRep;

        private readonly ShopCart _shopCar;

        public HomeController(IAllCars carRepository)
        {

            this._carRep = carRepository;
            

        }
        public ViewResult Index()
        {
            var homeCars = new HomeViewModel()
            {
                FavCars = _carRep.getFavCars
            };
            

            return View(homeCars);
        }


    }
}

Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {

        private readonly IAllOrders Allorders;

        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.shopCart = shopCart;
            this.Allorders = allOrders;
        }

        public IActionResult Checkout()
        {


            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItem = shopCart.getShopItems();
            if (shopCart.listShopItem.Count == 0)
            {
                ModelState.AddModelError("", "У вас должны быть товары!");
            }
            if (ModelState.IsValid)
            {
                Allorders.createOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан!";
             return View();
        }
    }
}

Shop/Controllers/ShopCarController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModel;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Shop.Controllers
{
    public class ShopCarController : Controller
    {
        private readonly IAllCars _carRep;

        private readonly ShopCart _shopCar;

        public ShopCarController(IAllCars carRepository, ShopCart shopCart) {

            this._carRep = carRepository;
            this._shopCar = shopCart;
            
        }

        public ViewResult Index()
        {
            var items = _shopCar.getShopItems();
            _shopCar.listShopItem = items;
            var obj = new ShopCartViewModel
            {
                shopCart = _shopCar
            };

            return View(model: obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _carRep.AllCars.FirstOrDefault(i=>i.id==id);
            if (item != null)
            {
                _shopCar.AddToCar(item);
            }
            return RedirectToAction("Index");
            


        }

    }
}

Shop/Views/Cars/List.cshtml
<h1>
    <h3>@Model.currentCategory</h3>
    Все автомобили
</h1>
@{
    foreach (Car car in Model.allCars)
    {
        @Html.Partial("AllCars", car)
    }

}

Shop/Views/Home/Index.cshtml
@model HomeViewModel


<h1>
   
    Best cars
</h1>
<div class="row mt-5 mb-2">
    @{ 
        foreach(Car car in Model.FavCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

Shop/Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-controller="Order" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-5">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="adress"></label>
            <div class="col-md-5">
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Заказать"/>
    </form>
</div>

Shop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Shop/Views/Shared/AllCars.cshtml
@model Shop.Data.Models.Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.img" />
    <h3>Model: @Model.name</h3>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c")</p>
    <p> <a class="btn btn-warning" asp-controller="ShopCar" asp-action="addToCart" asp-route-id="@Model.id">Добавить в корзину</a></p>
   
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top  bg-dark">
            <a class="navbar-brand" href="#">CarShop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index" >Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/electro">Electro Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/fuel">Classic Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCar/Index">Basket</a>
                    </li>
                </ul>
                @*<form class="form-check-inline mt-2 mt-md-0" >
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" />
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>*@
            </div>
       
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#"> Back to top</a></p>
        <p>2021 Company, Inc. <a href="#">Privacy</a> . <a href="#">Terms</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>

</body>
</html>
 

Shop/Views/ShopCar/Index.cshtml
@model ShopCartViewModel
<div class="container">
    @foreach(var element in Model.shopCart.listShopItem)
    {
        <div class="alert alert-warning mt-3"  >
            <b>Car: </b>@element.car.name<br/>
            <b>Price: </b>@element.car.price.ToString("c")
        </div>
    }
    <hr/>
    <a class="btn btn-danger " asp-controller="Order" asp-action="Checkout" >Pay </a>
</div>